### ISSUE TITLE
I get Unable to find the service

### ISSUE THREAD

**Issue by dovip** [MarLoe/VMware.PreferencePane#12]
![image](https://user-images.githubusercontent.com/1763104/44306505-dba23f80-a398-11e8-9ae9-2d1a89347bc4.png)

i use macOS High Sierra 10.13.6
on VMware workstation 12 on windows 7

**Comment by MarLoe** [comment]
Hi @dovip 

Thank you for using my preference pane 😃 
It seems like this is the response from the "vmware-resolutionSet" command line tool, which is what I call behind the scene.

You can try this from a terminal window:
`/Library/Application\ Support/VMware\ Tools/vmware-resolutionSet 1280 800`

That will most likely give you the same error message 😞 

I cannot provide support for the VMware Tools. However there is one thing that pops into mind:

Have you remembered to accept the VMware extension in the system preferences after you installed VMware Tools? Please see this link for more information. I know it targets Fusion, but it should be the same in your case.
[How to Install VMware Tools on macOS Sierra](https://kb.vmware.com/s/article/2151770)

I hope things sort out for you. Please let me know how it goes.

/Martin

**Comment by kevinmcox** [comment]
I've seen this error on almost every install and as Martin said it is related to the VMWare Tools, not the Pref Pane.

The easiest solution I've found is to install the Tools, accept the extension in System Preferences. Reboot. Uninstall the Tools, then re-install the Tools. I don't get prompted to accept on the second install and everything (command line and pref pane) starts working just fine.

That said, I'm installing it all via Munki (as root) so I'm not sure if I installed them manually in user space if it'd make a difference or not.

**Comment by MarLoe** [comment]
Thank you for your input @kevinmcox 
Much appreciated!

**Comment by dovip** [comment]
Thank you very much for your willingness to help, I will check

Dovi

**Comment by archongum** [comment]
> I've seen this error on almost every install and as Martin said it is related to the VMWare Tools, not the Pref Pane.
> 
> The easiest solution I've found is to install the Tools, accept the extension in System Preferences. Reboot. Uninstall the Tools, then re-install the Tools. I don't get prompted to accept on the second install and everything (command line and pref pane) starts working just fine.
> 
> That said, I'm installing it all via Munki (as root) so I'm not sure if I installed them manually in user space if it'd make a difference or not.

Uninstall and re-install  VMWare Tools works for macOS  10.14.2 on VMware workstation 15 Pro on windows 10 17763.316

**Comment by eturk1** [comment]
thanks for tip to reinstall! 
Just needed run install again, not uninstall.

**Comment by facilitycompass** [comment]
Manually install the tool using this command
`ps -audilhan|grep -i vmware`
> replace -audilhan with `-au<your user name>`

Then run this command 
`"/Library/Application Support/VMWAre Tools/vmware-resolutionSet" 1920 1080`

**Comment by Martifan** [comment]
After solving with Unlocker, it was found that the resolution became 1024*768, no matter how to change it, various methods on the Internet were used: for example, the nvram command line is invalid/edit com.apple.Boot.plist, enter recovery or not enter/install Vmsvga2 /guestd patch etc. will not work.

It is said on the Internet that it is now vmware-resolutionSet, but after I run it, it reports: Unable to find the service

I was puzzled, but I found that I missed a place, as shown in the figure: VMWare allows it, and the resolution can be adjusted freely.

System Preferences -> Security and Privacy -> General
![image](https://user-images.githubusercontent.com/7662702/120531030-3644a300-c3ef-11eb-9a96-195ddcf1d235.png)
