### ISSUE TITLE
Installation issue for MacOS 10.15 Beta 2 (Catalina)

### ISSUE THREAD

**Issue by siapplebaum** [MarLoe/VMware.PreferencePane#16]
There appears to be a permissions issue...

**Comment by MarLoe** [comment]
Thanks for the heads up @siapplebaum 
I have not yet had the stomach to install Catalina as a VM.

Can you supply me with some more info on this? Screen dumps, log files, anything relevant

Thank you,
Martin

**Comment by gerstemann** [comment]
Worked for me on Beta 3 ! I just had to install the VMware Tools twice.
So Install, allow access in the security panel für all vmware stuff, install vmware tools again. and voila, it worked for me including the panel. great work btw. @MarLoe

**Comment by MarLoe** [comment]
Thank you @gerstemann
I appreciate the feedback. Let’s see if beta 4 will eliminate the double installation issue...

**Comment by MarLoe** [comment]
@gerstemann, I have now tested on macOS Catalina 10.15.4 and it runs smoothly - besides the installation hickups (see README.md). So I am closing this issue now.
