### ISSUE TITLE
VMware.PreferencePane

### ISSUE THREAD

**Issue by raysami61** [MarLoe/VMware.PreferencePane#18]
i can't find way to to it
cp -r VMware.prefPane ~/Library/PreferencePanes/
in terminal i got error when i copy this to the terminal 
please some staps how to copy and what i copy all files & sub maps or just one ??
please help for dummy

Ray

**Comment by MarLoe** [comment]
What error are you getting?

**Comment by raysami61** [comment]
i will make screen dump & send it to you
ray











  Remon Sami  

 

Ray_sami@yahoo.com

 

http://www.linkedin.com/in/remonsami




 



 

    On Saturday, November 9, 2019, 04:39:22 PM GMT+1, Martin Løbger <notifications@github.com> wrote:  
 
 
What error are you getting?

**Comment by raysami61** [comment]
the copy command not working & go to directry access dinaed ??!!!i am admin & i think every thing open in this mac
take a look at the photo & let me know what i can do to get full access to all folder



ray











  Remon Sami  

 

Ray_sami@yahoo.com

 

http://www.linkedin.com/in/remonsami




 



 

    On Saturday, November 9, 2019, 04:39:22 PM GMT+1, Martin Løbger <notifications@github.com> wrote:  
 
 
What error are you getting?

**Comment by raysami61** [comment]
i used the command sudo su to get admin in terminalafter than the command to go to directory preferncepane but he can't find it ????














  Remon Sami  

 

Ray_sami@yahoo.com

 

http://www.linkedin.com/in/remonsami




 



 

    On Saturday, November 9, 2019, 04:39:22 PM GMT+1, Martin Løbger <notifications@github.com> wrote:  
 
 
What error are you getting?

**Comment by MarLoe** [comment]
I have update the [README.md](https://github.com/MarLoe/VMware.PreferencePane/blob/master/README.md) with improved installation instructions among other.

I am closing this issue. Please open a new if the problem persists.
