### ISSUE TITLE
“VMware.prefPane” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by melmaninga** [MarLoe/VMware.PreferencePane#19]
FYI

Catalina requires all software to be signed with developer IDs and to be 'notarized' by Apple. In the absence of an updated version from the developer, you can remove the quarantine Extended Attribute on the file:

sudo xattr -d com.apple.quarantine /Library/PreferencePanes/VMware.prefPane

Naturally, this bypasses Apple's security precautions which exist to stop maliciously altered software from running...

**Comment by MarLoe** [comment]
@melmaninga, your workaround has been put in the [README.md](/MarLoe/VMware.PreferencePane/blob/master/README.md#macos-catalina).

I have also tried to explain the "official" way of installing un-notarized preference panes.

I am still looking into a way around this or actually notarizing it. If anyone has suggestions or inout to notarizing a preference pane, please let me know.

**Comment by MarLoe** [comment]
Added an installer - it simplifies the installation. Still need to have it notarized...
