### ISSUE TITLE
How to remove/uninstall?

### ISSUE THREAD

**Issue by klepp0906** [MarLoe/VMware.PreferencePane#20]
First, thanks for the time and effort it took to put this together.  I figure I may need it at some point (even though i dont at this instant)

I installed it just as a dry/test run and facepalmed since I didnt make a snapshot prior which would have saved me harassing you.

How does one uninstall/remove the pane?

**Comment by klepp0906** [comment]
yea, that was easy.  probably should have tried the easy thing before asking!

**Comment by MarLoe** [comment]
Need to add an "Uninstall" section to readme 😄

**Comment by klepp0906** [comment]
i mean... will save you the odd rare occurrence of a post like this,  but in all honesty i should have right clicked before posting.  

but hey if it helped you flesh out/be more through with the information on the page.  Small win.  I'll take it lol.

**Comment by MarLoe** [comment]
@klepp0906, it's yours 🤪

**Comment by MarLoe** [comment]
Uninstall section added
