### ISSUE TITLE
Unable to retain resolution

### ISSUE THREAD

**Issue by Magurosenbei** [MarLoe/VMware.PreferencePane#8]
I am using OSX 10.13 on VMware workstation 14.
The panel has helped me resized the screen resolution to 1920x1080.
However, for some reason it automatically reverts to 960x540 (HiDPI).
Is there a setting that I have missed or something else is hindering the scaling?

**Comment by Magurosenbei** [comment]
Okay I found the solution to disable the behavior

Edit the file
`~/Library/Preferences/com.vmware.tools.plist`
with
```
<key>enableAutoHiDPI</key>
<false/>
```

**Comment by MarLoe** [comment]
Hi @Magurosenbei 

I just made a new [release 1.6.0](https://github.com/MarLoe/VMware.PreferencePane/releases/tag/v1.6.0) that allows you to switch this setting from the preference panel.

Hope it will help you and others in the same situation.
